name: CI
on: push
jobs:
  deploy:
    needs: test
    runs-on: ubuntu-latestif: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - run: echo "Deploying, beacuse this is main"
